# Generated by Django 5.0.6 on 2024-06-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
